modLoader = "kotlinforforge"
loaderVersion = "[3,)"
license = "Insert License Here"

[[mods]]
modId = "tkmm"
version = "${version}"
displayName = "TKM Manager"
authors = "ChAoS_UnItY"
description = '''
WIP
'''
#logoFile = ""

[[dependencies.tkmm]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tkmm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tkmm]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[${kotlin_for_forge_version}]"
ordering = "AFTER"
side = "CLIENT"